# Generated by Django 4.2 on 2023-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Cybersecurity', 'Cybersecurity'), ('Tech in Africa', 'Tech in Africa'), ('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'JavaScript'), ('HTML and CSS', 'HTML and CSS'), ('Tutorials', 'Tutorials'), ('General Tech', 'General Tech'), ('Industry-Specific Tech', 'Industry-Specific Tech')], max_length=240),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
