# Generated by Django 4.2 on 2023-05-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_title_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
